### ISSUE TITLE
Editing reply to a comment and saving with enter key

### ISSUE THREAD

**Issue by ThomasSchraml** [opencast/annotation-tool#143]
If in #113 a reply to a comment is edited and saved by using the enter key, the comment is not visible anymore. Only the edited reply is shown. After loading the tool again the comment is displayed again. When I use the the "Save" button after editing a reply, the comment is still visible.
![unbenannt](https://user-images.githubusercontent.com/35535980/40115591-43d778e0-5911-11e8-8ea1-9570b20877d5.PNG)
![unbenannt2](https://user-images.githubusercontent.com/35535980/40115595-45a654ac-5911-11e8-9237-e7543e72ec1f.PNG)

**Comment by JulianKniephoff** [comment]
This is not specific to #113; I can reproduce it already on 3f100ab.

However, I can not reproduce the part about reloading. When I reload after making the comment disappear, the tool does not load again because of an exception caused by the missing text in the comment.

This is in the development/localStorage mode; maybe the Opencast backend behaves differently.

**Comment by ebbertd** [comment]
This has been solved.
