### ISSUE TITLE
Export: Comments on annotations are not included

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#225]
In the export CSV-file the existing comments on annotations are not included - but they should. 
Possible solutions: Either... 
(a) comments get a separate column or 
(b) get written in the column «Value». 

In addition a new column called «Refers to» is needed. Here the ID of the annotation to which the comment belongs to is indicated. See attached an export from the old annotation tool working on SWITCHcast. All rows with a number in the column «Refers To» are comments on annotations.

[annotations.xlsx](https://github.com/opencast/annotation-tool/files/3156408/annotations.xlsx)

**Comment by dagraf** [comment]
Meiner Meinung nach ist das ein Bug und müsste eigentlich von SWITCH finanziert werden. Ich ergänze mal die Bugmeldung bei SWITCHcast. Falls sie jedoch sich nicht von sich aus melden, dann behebe diesen doch bitte auf unsere Kosten.

**Comment by JulianKniephoff** [comment]
Apparently this does not quite yet when the comments include newlines (at the end)? Here is an example export demonstrating that. 

Need to investigate further.

[export.txt](https://github.com/opencast/annotation-tool/files/4244080/export.txt)

**Comment by JulianKniephoff** [comment]
Okay, I think I solved it. See f008b0c2b9e008ac9bb69303004e042a1d0c0c48. I reopened #333.

**Comment by dagraf** [comment]
I still observe the same issue.

[export-5.txt](https://github.com/opencast/annotation-tool/files/4292498/export-5.txt)
<img width="1664" alt="Bildschirmfoto 2020-03-05 um 11 45 32" src="https://user-images.githubusercontent.com/15246287/75974539-419cdc00-5ed7-11ea-8143-0eb1832376fd.png">

**Comment by JulianKniephoff** [comment]
Wait but that looks all wrong anyway. The commas and quotation marks shouldn't be there either. How exactly are you opening that file? Can you specify any settings while doing so? A cursory look into similar problems suggests that Excel behaves differently depending on how you open a CSV, for example an implicit import from within the app vs. just double clicking a CSV on your Desktop.

The file itself and the code producing it is fine, I'm pretty sure. LibreOffice opens it fine and manually inspecting it I can also not see any non-conformities. I think Excel is the problem here. :thinking:

**Comment by dagraf** [comment]
See screencast
[Open CSV-file with excel.mp4.zip](https://github.com/opencast/annotation-tool/files/4292776/Open.CSV-file.with.excel.mp4.zip)

**Comment by JulianKniephoff** [comment]
Unfortunately I can't really read the text in the dialog boxes, can you post a readable screenshot of the two option panels after selecting the file? :sweat_smile:

**Comment by dagraf** [comment]
Sorry. Something went wrong while exporting the video...
<img width="804" alt="Bildschirmfoto 2020-03-05 um 13 05 10" src="https://user-images.githubusercontent.com/15246287/75980054-0fdd4280-5ee2-11ea-84bc-53d0ddd10550.png">
<img width="788" alt="Bildschirmfoto 2020-03-05 um 13 04 58" src="https://user-images.githubusercontent.com/15246287/75980059-1075d900-5ee2-11ea-987e-8609fef7ecf9.png">
<img width="824" alt="Bildschirmfoto 2020-03-05 um 13 04 48" src="https://user-images.githubusercontent.com/15246287/75980061-110e6f80-5ee2-11ea-9352-d5234c2a93f0.png">
<img width="534" alt="Bildschirmfoto 2020-03-05 um 13 04 39" src="https://user-images.githubusercontent.com/15246287/75980062-11a70600-5ee2-11ea-9a10-15c0e1cd846f.png">
<img width="313" alt="Bildschirmfoto 2020-03-05 um 13 04 32" src="https://user-images.githubusercontent.com/15246287/75980063-123f9c80-5ee2-11ea-8070-f52e45659cd4.png">





<img width="821" alt="Bildschirmfoto 2020-03-05 um 13 05 18" src="https://user-images.githubusercontent.com/15246287/75980044-0c49bb80-5ee2-11ea-99cc-8517945907e3.png">

**Comment by JulianKniephoff** [comment]
What else can you select under "Dateiursprung"? I suspect that's the problem. The file is not coming from a Mac, but from a Linux box. And since the only reason why they would need that information is to know how line separators should look in the file, it fits our issue at hand.

Note that that is a "bug" in Excel: CSV line endings are specified to always be `\r\n`, independent of the producing operating system. But many implementations ignore that fact conveniently, making life harder for everyone. Maybe just try every option under "Dateiursprung".

**Comment by dagraf** [comment]
Grmpf. Okay then...

**Comment by JulianKniephoff** [comment]
So does it work with one of the options there?

**Comment by dagraf** [comment]
Did try some. None of them worked.

**Comment by dagraf** [comment]
New finding: This bug in Excel does only appear with comments that were inserted by pressing «Enter». All comments inserted using the «Insert» button look fine.

Could that help to solve the problem?

**Comment by JulianKniephoff** [comment]
Can you try inserting a comment that has a linebreak in the middle of it (for example via copy and paste), and then see how Excel deals with that?

So creating a comment with enter apparently inserts a newline character at the end. That is a minor bug that we could/should fix, but I would still like to know whether inline newlines break Excel, too. :thinking:

If not, then we could just strip off any trailing newlines, I don't think that should be a problem. However, I would hesitate to remove **all** newlines unconditionally, only to satisfy Excel, which is clearly the culprit here.

**Comment by dagraf** [comment]
I tested as asked. For each linebreak does excel show a new line.

Anyhow it would be great to get rid of this minor bug you mentioned.

**Comment by JulianKniephoff** [comment]
Oof that sucks. :thinking: 

The only reasonable thing I can think about is to add an export dialog where one can optionally strip the newlines out before exporting, if one wants to use it with Excel.

Or maybe there **is** some way to convince Excel to accept the newlines somehow and then that option could enable that "hack".

**Comment by dagraf** [comment]
What about this: 
- For the moment: Fix the minor bug that creating a comment with enter inserts a newline character at the end.
- For the future: Offer an xlsx-export option. This is a feature the univeristy of Fribourg (CH) wants to fund (see personal mail from 26.2.2020).

**Comment by JulianKniephoff** [comment]
Sounds reasonable to me. :+1:

**Comment by dagraf** [comment]
Looks fine. Thx!
