### ISSUE TITLE
Annotation tool is unable to start

### ISSUE THREAD

**Issue by Lyliian** [opencast/annotation-tool#226]
Hello, since i did an update of the annotation tool, this one refused to start.
As you can see in the log file there is 2 issues : 

![image](https://user-images.githubusercontent.com/12525724/57604008-62203200-7563-11e9-884d-b59018bfd759.png)

Can someone help me ? 

Lylian.

**Comment by Lyliian** [comment]
And this is what we have when we are trying to use Annotation-tool : 

![image](https://user-images.githubusercontent.com/12525724/57604122-af040880-7563-11e9-9050-d56f4363b3e7.png)

**Comment by JulianKniephoff** [comment]
It worries me a bit that JAX-RS seems to be one of the problematic modules here, but in general my first questions in the case of these OSGi errors are always:

- What exact version of Opencast are you trying to run this in?
- What exact version did you build the annotation tool against (`-Dopencast.version` flag)

While there are some cases where different answers to these questions are compatible, things are easiest when they are identical, where `6.x` (as in the branch, with a literal `x`, not where `x` stands for something like `4`) maps to `6-SNAPSHOT`.

Also note that at least when I last checked, the POMs you get for released (i.e. non-snapshot) versions of Opencast, from the official Maven repos, do not work as they do not include dependency information for some reason. If you want to build against a specific release as opposed to a snapshot, you might want to build that release locally yourself, first, so that the artifacts (including the correct POMs) are in your local Maven repository.

**Comment by Lyliian** [comment]
My exact version of Opencast is 6.4.
And the exact version i build against -Dopencast.version flag is 6.4 too.

**Comment by mliradelc** [comment]
Hi @Lyliian 

Try this, I got the same problem as you, @mtneug gave me this solution that worked for me:

> Hi, 
> 
> yes the bundle load order is not always correct for bundles in the deploy folder. As Julian said you can delay the loading by editing `etc/org.apache.felix.fileinstall-deploy.cfg`. Below is what we are using: 
> 
> ```
> felix.fileinstall.dir           = ${karaf.base}/deploy 
> felix.fileinstall.tmpdir        = ${karaf.data}/generated-bundles 
> felix.fileinstall.poll          = 30000 
> felix.fileinstall.start.level   = 80 
> felix.fileinstall.active.level  = 80 
> felix.fileinstall.log.level     = 3 
> ```
> 
> – Matthias

**Comment by Lyliian** [comment]
@mliradelc WOW ! It's working now. Thank's a lot.

Regards,

Lylian.

**Comment by mtneug** [comment]
I will close this then 🙂
