### ISSUE TITLE
Who can share me the working 4 compiled jar files against the 6.6 Opencast?

### ISSUE THREAD

**Issue by fishfree** [opencast/annotation-tool#254]
I spend too much time on getting it working with Opencast, but always no luck. So, I want to have a try with your working files, please.

**Comment by JulianKniephoff** [comment]
No offense, but this issue tracker is supposed to track issues and tasks the maintainers (i.e. me) are supposed or want to do at some point. Your title suggests that this is a request towards the community, which is better served on a community platform. Since the annotation tool does not have something like that at the moment, I would direct you towards on of the Opencast mailing lists. See also [here](https://docs.opencast.org/#communication-help).

For a general solution, we already have #250 to remind me to provide what you want in a a way easily consumable by everyone. I even changed the title just now to reflect that. :wink:

**Comment by JulianKniephoff** [comment]
FWIW: You **could** try to gather the necessary jars from here: https://github.com/opencast/annotation-tool/tree/m2/org/opencast/annotate
