### ISSUE TITLE
New feature: Category related to a single event or all event of a series

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#260]
At the moment categories are always related to a single event. This new feature should give the administrator/user the opportunity to relate categories to a single event or to all event of a series.
Suggestion for implementation:
- as option showing up in an overlay when I click on the plus-button to create a new category
- for existing categories: Modifiable via the "Pen" icon

**Comment by JulianKniephoff** [comment]
### What would need to happen?

* The `categories` table has to get a new column à la `series_ext_id`
  * We might also consider adding a `series` table if we want to store additional metadata about series, but I can't think of any right now, so why make it more complicated?
    * And it would make it more complicated, because we have to populate that table somehow
      * How awkward this **can** get can be seen very nicely in the code that does it for the `videos` table
* The API needs to learn how to create categories that belong to a series vs. to an episode
* The frontend actually needs to know about the series a video belongs to
  * We can get this from either search or the external API, depending on the backend implementation (community vs. SWITCH), that shouldn't be a problem
  * And we can just communicate it in the same step where the tool gets a hold of the video itself
* The category related domain logic in the frontend needs to be adapted
  * We need to fetch the categories that belong to the series of the video
  * Import/export needs to be adapted
* The UI needs to offer the new functionality somehow

### Open questions

* What happens if a video is moved to another series?
  * In the approach outlined above, we would then "lose" the categories that belonged to a series

**Comment by JulianKniephoff** [comment]
An alternative suggestion by @rrolf could look like this:

Instead of adding an indirection where the tool would manage the categories from the video and from its series "individually", we could just add a very simple synchronization in the sense that when the tool starts up, we look up whether there are any categories associated with a video's series, and if so, copy them over to the video, so that they just become categories on the video.

They would remember that they came from a category from a series, and if we change it, it would have to push these changes upstream, so to say. The next time the tool is started, these changes then propagate to the next video that is opened.

This might be slightly less complex in its implementation than what I proposed, (and thus less expensive :wink:) at the expense of a bit more complexity in the data, put very simply.

The big benefit is that it would solve the open question above. A video would not get its categories from its current series every time and forget about them in the end, it would keep them.

However, this approach adds other complications one would need to think about: If we move a video between series, it would now get the categories of two series, and an interesting question is for example whether we can still manipulate the categories of its old series through it.

**Comment by JulianKniephoff** [comment]
@dagraf thinking about this some more still leaves the following question open, independently of how we implement this change:

Say we mark a category as belonging to a series. What should happen with that category, when any video from that series is moved to another series, or loses its series altogether?

When I go to any other video of the old series, I presume the category should still be there, right?

But what if I go to the moved video? Should the category also still be there?

If yes, should it still sync changes to it back to the old series? That is, should I see changes I make to the category through the moved video when I go to any other video of the old series?

What happens if I go to any other video of the **new** series? Should I also see this category now?

Or should the category just "decay" to a "per event" category, and I have to manually and explicitly say that it again belongs to the series, which is now the new series?

We could also imagine making this configurable, but in the interest of maybe possibly still having the slightest chance to get this into the next SWITCHcast release, we should probably concentrate on your specific use case, first.

**Comment by dagraf** [comment]
@JulianKniephoff 
My suggestion would be not to make it configurable and to choose this solution: 

- When a video gets moved to another series or loses its series, the category decay to a "per event" category for the moved video. So it looses its connection to the old series > no sync changes to/from the old series.
- The videos in the new series do not see the categories of the moved video by default. But I can alter the settings of the categories of the moved video from "per event" to "per series".
- The remaining videos of the "old" series still carry their categories because they belong still to the old series.
-

**Comment by JulianKniephoff** [comment]
@dagraf okay, I will go with solution for now. :smiley: 

You bring up another good point. The naive approach would probably lead to duplicates, yes, but a simple check for a "sufficiently equal" preexisting category should not be too difficult, I suppose. :thinking:

**Comment by dagraf** [comment]
Moved back to "backlog".

**Comment by dagraf** [comment]
Is in production and can therefore be closed.
