### ISSUE TITLE
Color of categories: Altering the colour of a category has no effect on already existing annotations

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#284]
When I change the colour of a category I would expect that all already existing annotations of this category also change its colour. At the moment this is not the case.

**Comment by JulianKniephoff** [comment]
This actually hints at a larger issue within the annotation tool: The links between scales/scale values, categories, their labels and the annotations carrying them are currently rather "weak", and unfortunately also inconsistently so. For example: If I change the text of a label, the text of all the annotations carrying that label does not change, I think. Some things like that, and also the color of a category, are just copied down to their corresponding "child entities". This **can** be intended; immutability makes things easier to reason about, not only in programming. (Why did my annotation in video X suddenly change?! I didn't do anything! Turns out **another user** changed a **related** entity. That can be confusing.) However, I can also understand the desire for a consistent state of the data.

Anyway, we should be explicit and also probably somewhat consistent with this. So my question would be to @dagraf, and also to other adopters (/cc @ebbertd), what do you think?

* Should color changes of the category effect old annotations carrying that category's labels?
* Should changes to the text of a label affect old annotations carrying that label?
* Should changes to a scale value's value and text affect old annotations?
* What happens to preexisting annotations that have a label of some category which does not have a scale, when I suddenly assign that category a scale?
* What happens to "child entities" when we delete their (grand*)parents?
  * When we delete a category, it should probably delete all the labels under it, right?
    * But what about the annotations that carry these labels?
  * When we un-assign a scale from a category, should we really forget all the scale values on all the annotations that have labels of that category?
  * When we delete a scale value, but a category still has its parent scale assigned, what should happen to annotations that had that scale value?
* (What other similar things should we consider?)

Especially the last points make this a hard problem and almost force this "weak link" behavior, when we want something consistent.

**Comment by dagraf** [comment]
@JulianKniephoff I totally understand that this weak link has its reasons and I have no best solution for all your questions. Do you?

I would suggest to only link the color harder and to leave everything else as it is. Because the possible confusion you mention is higher when someone changes the color of a category (parent) suddenly all annotations in my track using this category (its childrens) have a color with no corresponding parent.

**Comment by ebbertd** [comment]
The original issue, that the color of the annotations doesn't change with the category has been solved.
