### ISSUE TITLE
Playhead should only be pullable on the timeline not on the track itself

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#287]
When selecting an annotation the playhead jumps to the beginning of this annotation. I then want to alter the start of this annotation: When hovering over the start of this annotation I can only drag the playhead. To be able to alter the start of the annotation I have to go slightly to the right.

Possible solution -> see title of this issue

**Comment by JulianKniephoff** [comment]
I'm not sure I agree with this solution. Always having to grab the little triangle is way too finicky. Also, wen I am looking at a track and I want to move the playhead to a specific position in that track, I don't want to have to go for the triangle first; I want to look at the position I want to go to, grab the red line which I hopefully see in my peripheral vision somewhere, and put it where I want it. :thinking: 

Also, while I do agree with the interaction not being ideal, I don't think it's that bad: The handles with which you can resize an annotation extend slightly into the timeline item, so you can still grab it, even with the playhead covering the very beginning of it. Additionally, your cursor should indicate which action a drag would take in your current cursor position, i.e. when hovering over the playhead, it should be different than from when hovering over the resize handles. If that's not the case, that's a bug.

Alternative solution: The problem mainly exists because I have to select an item first before I can resize it, but the tool also takes that as a cue to move the playhead to the beginning of that annotation. Maybe we could change something else in that sequence?

Ideas:

* Selecting an annotation does not move the playhead
  * Maybe you have to double click for that, or Ctrl+click
  * Or clicking remains as it is, but you can Ctrl+click to **just** select
* Selection should not be necessary for moving/resizing
  * This has the problem that if your timeline is very full, and you are zoomed in, the actual timeline-part on the timeline (the strip with the times at the top) can quickly become the only safe place to click and drag to scroll the entire timeline

Thoughts? What do @ebbertd and @rrolf think?

**Comment by dagraf** [comment]
I get your point. But it is important that the playhead always jumps to the beginning of an annotation when clicking on it. This feature is very often used when rewatching analysed videos in seminar or similar settings. 
Therefore I would suggest:
- Forget about what this ticket was about (you could close it if you like).
- Add the option Ctrl+Click to **just** select an annotation.
- Make it possible to drag the playhead on the timeline.

What do you think?

**Comment by JulianKniephoff** [comment]
I think that sounds reasonable. I will have a look at whether/how the library can (be made to) support this. :)

**Comment by JulianKniephoff** [comment]
In light of #331, this can now definitely be closed.
