### ISSUE TITLE
Annotations can not be moved when I not immediately move the mouse after clicking on the annotation

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#290]
See screencast: I can only move an activated annotations if I immediately move the cursor after clicking and not releasing the mouse-button. If I wait a little before moving the cursor (but do not release the mouse-button) the annotation gets deactivated and I can not move the annotation.

[Annotation Tool_Annotation verschieben.mp4.zip](https://github.com/opencast/annotation-tool/files/3978193/Annotation.Tool_Annotation.verschieben.mp4.zip)

**Comment by dagraf** [comment]
Did you alter already something? Now I get a different bug: I can only move an annotation when it is not yet activated by clicking on it, not releasing the mouse button and move the mouse. I am not able to move an already activated annotation. Because when clicking on it again it gets deactivated. This should not be the case.

In the old annotation tool, only already selected annotations could be moved. So users first have to click on a annotation and then click again on it to move it.

**Comment by JulianKniephoff** [comment]
Memo to myself so that I don't forget where to continue investigating this tomorrow: This happens because when you click and hold without moving, the timeline library sends the selection event again. We capture this and relay it internally. However, our internal selection logic works like this: If you select something that is already selected, the selection is canceled.

**Comment by JulianKniephoff** [comment]
New finding: I think that initial event is sent because of the "long press" interaction that the timeline supports for selecting multiple items on mobile devices. That is: After selecting an item by tapping on it, you could theoretically select further items by long-pressing on them.

However, I think this should not happen with mice/on the desktop, because it's a very unusual/unintuitive gesture there. I think I can fix this easily, though.

Another interesting point is that you can actually turn off the ability to select multiple items, or rather you have to explicitly turn it on if you want it, which we don't. So I think we might have found a bug in the timeline and this might be the first opportunity for ELAN to contribute something to that library. :smile:

**Comment by dagraf** [comment]
Works as expected on SWITCHcast-Test.

**Comment by dagraf** [comment]
Works as expected on SWITCHcast.
