### ISSUE TITLE
Different colours for selected and activated annotations is confusing (and not consistently implemented)

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#359]
It is hard to understand which coulour means what. In the end it confuses more than it helps. I suggest we only use the old version of highlighting active annotations and ged rid of the new one.

Here's whats not consistent:
- Single click= red
- Double click = red & Playhead jump to this position (correct would be YELLOW)
- Single click > double click on the same annotation = yellow & Playhead jump to this position

**Comment by JulianKniephoff** [comment]
The selected annotation should always be red IMO. Otherwise there is no way to tell whether it is selected or even whether there is an active selection at all. Of course if it is red, you can't see whether it is active, but that information is readable elsewhere: You can visually see whether the playhead intersects the annotation or not.

The reason I implemented this distinction is that the concept of the selection and the "active" annotations are not the same. They don't behave the same when you interact with them, etc., so I don't think they should look the same.

We could think about using different means of distinguishing them, so both statuses can be visible at the same time, though, instead of just the inner shadow color. Maybe an inner vs. outer shadow?

**Comment by dagraf** [comment]
I agree: The selected annotation should always be red. But then the colors should be the other way around: Selected = yellow; Active = red

But I do not see the need for this distinction between selected and activated annotations. Reasons:
1. Mainly because a user does not understand it right away what this different colors mean. 
2. If I select an annotation via single click and then the play head runs over it, I expect that it changes its color (at the moment from red to yellow), because now it is not only selected but also active. But it does not.
3. I do see no need to differentiate between direct double click (at the moment = red)  and double click after a single click (at the moment = yellow).

So please, get rid of the distinction.

**Comment by dagraf** [comment]
4. The most important thing for the user is to get indicated where he/she should look at or is working on. For this reason the one color is enough.

**Comment by JulianKniephoff** [comment]
> I agree: The selected annotation should always be red. But then the colors should be the other way around: Selected = yellow; Active = red
> 
Okay, we can discuss the colors, I don't have any hard opinion on the specifics, but I **do** think that the selection color should be more noticeable than the activation color, hence the current choice.

> But I do not see the need for this distinction between selected and activated annotations. Reasons:
> 
> 1. Mainly because a user does not understand it right away what this different colors mean.

I think the old behavior is more confusing. For example: It is not possible to "unactivate" an annotation by clicking it, but you can unselect a selected one. And in general in your scenario, clicking on some red annotations would behave different from clicking on others.

> 2. If I select an annotation via single click and then the play head runs over it, I expect that it changes its color (at the moment from red to yellow), because now it is not only selected but also active. But it does not.

But that doesn't happen when everything is red, either. And moreover, when the play head leaves the selected annotation behind, you are left wondering why it is still red, because you might not know for sure that it is selected. :thinking: But okay I will grant you the point that this is somewhat unexpected and my solution would be to introduce another "discriminator" beside the inner shadow color.

> 3. I do see no need to differentiate between direct double click (at the moment = red)  and double click after a single click (at the moment = yellow).
> 
When you double click a selected annotation, it gets unselected and the playehad jumps to it. I admit that I don't like that behavior, but it is a combination of constraints coming from the timeline library and the fact that I wanted to retain the ability to unselect annotations by clicking on them again. So a double click on an annotation is basically like a single click now, but it also moves the playhead.

The alternatives to that, as far as I see it, are to

* not make clicking a selected annotation unselect it
  * but then there is no way to unselect an annotation in the list view
* just handle every click individually as before
  * that would mean that double clicking a selected annotation would unselect it and select it again, but more annoyingly, double clicking an **unselected** annotation would select it, then unselect it again and placing the playhead there.

But I digress. The color change you describe is due to this behavior. You double click a selected annotation -> The playhead gets placed there so it is now active -> it is unselected.

Without the distinction, that annotation would still be red, but unselected now, which I still find very confusing.

> So please, get rid of the distinction.

To be honest, I would really rather not. We can talk about the specifics, but reverting to the previous behavior is not really an option. Both, because I don't want, but also for some technical reasons: Implementing the double click behavior was only possible in a clean way by fixing some bugs in the old selection code. Some of the weirdness I mentioned below your first point are actually a result of these changes, but they are arguably the more correct behavior, because for example previously, the tool couldn't even distinguish between selected and active annotations reliably internally, and so you could unselect active annotations although they should actually still be active. That could throw off the "automatic opening and closing of active annotations" sometimes and stuff like that.

The internal distinction is actually on my TODO list for a long time now, and it was necessary for something that you wanted. The visual distinction is not something that you wanted, I get that, but it was also just a less than 5 minute change, that I made because I think it is the right thing to do for the project. :thinking:

**Comment by dagraf** [comment]
Our top priority should be the behavior a user expects. I think we should quickly discuss this thoroughly in an online meeting. Do you have time today? I do, expect from 3-4pm.

See some remarks below.

> > But I do not see the need for this distinction between selected and activated annotations. Reasons:
> > 
> > 1. Mainly because a user does not understand it right away what this different colors mean.
> 
> I think the old behavior is more confusing. For example: It is not possible to "unactivate" an annotation by clicking it, but you can unselect a selected one. And in general in your scenario, clicking on some red annotations would behave different from clicking on others.

Your example is perfectly possible with the old bevahior: I can make the red frame of an active annotation disappear by clicking on it. 

 
> 
> > 1. If I select an annotation via single click and then the play head runs over it, I expect that it changes its color (at the moment from red to yellow), because now it is not only selected but also active. But it does not.
> 
> But that doesn't happen when everything is red, either. And moreover, when the play head leaves the selected annotation behind, you are left wondering why it is still red, because you might not know for sure that it is selected. 🤔 But okay I will grant you the point that this is somewhat unexpected and my solution would be to introduce another "discriminator" beside the inner shadow color.

Yes, it does not change the color when everything is red. That's exactly what I want.
Tor your "moreover": I prefer living with selected annotations not getting "unframed" when the play head leaves the selected annotation behind than with all the other unexpected stuff.
 
> > 1. I do see no need to differentiate between direct double click (at the moment = red)  and double click after a single click (at the moment = yellow).
> 
> When you double click a selected annotation, it gets unselected and the playehad jumps to it. I admit that I don't like that behavior, but it is a combination of constraints coming from the timeline library and the fact that I wanted to retain the ability to unselect annotations by clicking on them again. So a double click on an annotation is basically like a single click now, but it also moves the playhead.

As a user I do not expect an annotation to be unselected when double clicking on it. So it would be an advantage if selecting and activating have the same color: The users does not get confused.

> The internal distinction is actually on my TODO list for a long time now, and it was necessary for something that you wanted. The visual distinction is not something that you wanted, I get that, but it was also just a less than 5 minute change, that I made because I think it is the right thing to do for the project. 🤔

We think (I discussed it with colleagues, so it's not only my opinion) it's not the right thing to do. And if it was less than 5 minute of change, please get rid of it an we can try how the user experience it.

**Comment by dagraf** [comment]
> 
> But I digress. The color change you describe is due to this behavior. You double click a selected annotation -> The playhead gets placed there so it is now active -> it is unselected.
> 
> Without the distinction, that annotation would still be red, but unselected now, which I still find very confusing.

Yes, it is still red. But it is much less confusing than the different result of double clicking an annotation depending on its selection (selected or deselected).

**Comment by dagraf** [comment]
To sum up again: The most important thing for the user is to get indicated where he/she should look at or is working on. The differentiation between selected and active is less important.

Important to now why I insist on the one color:
- I didn't want the distinction between the two colors.
- The reason why we implemented the distinction between single and double click (which made you introduce the two colors): the click-wideness of the red line covers the whole clickable region of newly inserted annotations. And this click-wideness of the red line you didn't not want to change.

**Comment by JulianKniephoff** [comment]
> Our top priority should be the behavior a user expects. I think we should quickly discuss this thoroughly in an online meeting. Do you have time today? I do, expect from 3-4pm.
> 
We should discuss this and other things in a meeting, you will get an email from me. But I can't let some things just sit unanswered here, I'm sorry. :sweat_smile: 

> See some remarks below.
> 
> > > But I do not see the need for this distinction between selected and activated annotations. Reasons:
> > > 
> > > 1. Mainly because a user does not understand it right away what this different colors mean.
> > 
> > 
> > I think the old behavior is more confusing. For example: It is not possible to "unactivate" an annotation by clicking it, but you can unselect a selected one. And in general in your scenario, clicking on some red annotations would behave different from clicking on others.
> 
> Your example is perfectly possible with the old bevahior: I can make the red frame of an active annotation disappear by clicking on it.
> 

I **know** it's possible. What I'm saying is that that's a bug.

> > > 1. I do see no need to differentiate between direct double click (at the moment = red)  and double click after a single click (at the moment = yellow).
> > 
> > 
> > When you double click a selected annotation, it gets unselected and the playehad jumps to it. I admit that I don't like that behavior, but it is a combination of constraints coming from the timeline library and the fact that I wanted to retain the ability to unselect annotations by clicking on them again. So a double click on an annotation is basically like a single click now, but it also moves the playhead.
> 
> As a user I do not expect an annotation to be unselected when double clicking on it. So it would be an advantage if selecting and activating have the same color: The users does not get confused.
> 

If you don't want double click to unselect, the color does not matter. If that behavior is to be kept for whatever reason, though, having the same color is the actual confusing part, because it suggests that the annotation is still selected but it is not.

> > The internal distinction is actually on my TODO list for a long time now, and it was necessary for something that you wanted. The visual distinction is not something that you wanted, I get that, but it was also just a less than 5 minute change, that I made because I think it is the right thing to do for the project. thinking
> 
> We think (I discussed it with colleagues, so it's not only my opinion) it's not the right thing to do. And if it was less than 5 minute of change, please get rid of it an we can try how the user experience it.

As the de facto maintainer of this open source project, I think I am allowed to make some decisions on my own. The 5 minute fact was only mentioned to suggest that you do not have to fear that you paid for it or anything, but that also means that the decision to revert that change or not is not yours alone. Should it be mine alone? Probably not; if I don't listen to the community at all, the project is basically doomed to die, but the same is true IMO if the maintainer just blindly follows every client wish.

And so I suggested a compromise, and I also discussed this with Rüdiger, who agrees with the reasonableness of my change and independently came up with a similar compromise. We can and should discuss this further in a proper meeting, though.

**Comment by dagraf** [comment]
I am looking forward to the meeting. I'm shure we will find a decent compromise. 

In my opinition we need to fix these two things when we decide to stick to the two colors: 
1. The result of a double click (= annotation gets selected AND activated) must be independent of whether the annotation was already selected or not.
2. Selected AND active annotation must be specially marked. So both status must be visible at the same time (as you suggested above).

**Comment by ebbertd** [comment]
First of all, I think it's great that it is now possible to distinguish between active and selected annotations.

Although I have to agree that it can be confusing to have two colours which both are displayed as a frames around the annotation in the timeline. But, I also understand the need to distinguish between these two states. However, both states can also happen at the same time. A selected annotation can also be the active annotation which leads to the problem that it is not clear what should be displayed in that case. I suggest the following:

- The selected annotation is framed in red.
- The active annotation gets the inner shadow.
- A selected annotation that is also active would thus have a red frame and an inner shadow.

I have to admit that this is not really easier to notice, as it is a detail, but it has the advantage of reducing the number of colours needed which makes it easier to understand for new users and experienced users are still able to distinguish between the different states.

This suggestion could then lead to the following behaviour:

- When a user single clicks on a annotation, it gets the red frame.
- When the playhead then moves to the selected annotation the inner shadow is added.
- If the user now single clicks on the selected and active annotation the annotation is now longer selected and the red frame removed, but the inner shadow remains.
- When the playhead leaves the annotation the inner shadow is also removed.

Lastly I have to agree that the result of a double click should be independent of the previous state of the double clicked annotation. It should always lead to the double clicked annotation being selected and active. (Simply because it makes no sense to me to keep another selected annotation if one wants to jump to a different annotation.)

I hope this helps.

**Comment by dagraf** [comment]
When a free text annotations gets selected: Please make the grey strips slightly brighter as to improve contrast between the black text.

**Comment by JulianKniephoff** [comment]
@dagraf 

1. Now (the stripes actually being black with an opacity of `0.15`)
![image](https://user-images.githubusercontent.com/123272/90482242-3b23b900-e133-11ea-8903-8809e984379a.png)

2. Opacity `0.1`
![image](https://user-images.githubusercontent.com/123272/90482472-9190f780-e133-11ea-96f6-4e1f86bfb383.png)

3. Opacity `0.05`
![image](https://user-images.githubusercontent.com/123272/90482659-d7e65680-e133-11ea-9058-477b50ea9bb6.png)

One of those? Something in between? I prefer 1, but could live with 2 or something in between the two. I think 3. is too pale.

The problem I see with lower contrasts, even 2. already, is that the selection gets less noticeable for short annotations, where you really only get one line in, and it is probably covered by text. :thinking:

**Comment by dagraf** [comment]
I would prefer 2, but can live with 1. Should we agree on something in between? Meaning an opacity of 0.125?

FYI: When opening the annotation tool on SWITCHcast-Staging (https://unibe-ch.annotate.cast-test.switch.ch/) the differentiation between active an selected annotations do not get shown anymore. Could you please take care that I can test your bugfixes?

**Comment by JulianKniephoff** [comment]
> I would prefer 2, but can live with 1. Should we agree on something in between? Meaning an opacity of 0.125?
> 
Sounds fair :smile: 

> FYI: When opening the annotation tool on SWITCHcast-Staging (https://unibe-ch.annotate.cast-test.switch.ch/) the differentiation between active an selected annotations do not get shown anymore. It seems to me, that an older version of the annotation tool is running on cast-test.switch.ch. Could you please take care that I can test your bugfixes again?

Will do.

**Comment by dagraf** [comment]
After having having seen it now on the timeline I would no also prefer 1 (opacity 0.15).

But we still have a contrast issue in the list of annotations (see screenshot). Could you make the text black and not grey?
![Bildschirmfoto 2020-08-18 um 16 57 10](https://user-images.githubusercontent.com/15246287/90529418-fd935000-e173-11ea-90b2-15d458819cfc.png)

**Comment by JulianKniephoff** [comment]
@dagraf 
![image](https://user-images.githubusercontent.com/123272/90609115-dc7a4000-e203-11ea-986a-730d8c1604b5.png)
?

**Comment by dagraf** [comment]
Perfekt! Danke!

**Comment by dagraf** [comment]
Looks and works fine. Thx!
