### ISSUE TITLE
Distinguish between public and private categories in the "Mine" tab

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#396]
The different tabs in the categories panel currently conflate two properties of a category:

* Who created it (me vs. someone else)
* Who has access to it (only me vs. everybody)

So normal users can create categories only they can use/see, and they can use categories public to everyone which only admins can create. They can't however create categories that other normal users can use.

We might just want to let the user specify whether a category is public or private. An open question is still how to distinguish public categories from normal users from those created by the admins, which are probably "blessed" in some sense. :thinking:

**Comment by JulianKniephoff** [comment]
@dagraf wasn't there already an issue describing this? I couldn't find it, so I created this new one, but maybe you still have it somewhere? :sweat_smile:

**Comment by dagraf** [comment]
I think you mean this issue: https://github.com/opencast/annotation-tool/issues/224

**Comment by Arnei** [comment]
I am a bit confused on the goal of this issue. 

JulianKniephoff wants to allow all user to create public and private categories, and then somehow distinguish between categories created by users and categories created by admins.

This seems contrary to the issue references by dagraf. There, ebbertd states that allowing all users to create public categories can quickly render the tool unusable. Instead, a "shared with administrator" option for private user categories is proposed.

**Comment by dagraf** [comment]
@Arnei: You are totally right. https://github.com/opencast/annotation-tool/issues/224 describes our intention better than Julians comment. 

I try to sum it up here:
- When creating a new or editing an existing category in the tab "Mine" I can choose between 3 sharing options: "Public / Shared with administrator / Private". Appropriate but short explanations are needed for each option.
- Offer these options in the modal "Edit category". Default = "Private"
- When clicking the "+"-Icon to create a new category the modal "Edit category" gets opened. Here I can set the title, chose sharing options and a scale.
- When an admin or user selects a 'foreign' track which has one or more public or shared-with-administrator "Mine"-categories: A new tab appears in the category window named after this other user ("Name, Surename") and all annotations belonging to this category are shown. 
- This foreign category is shown in 'read-only' mode.

**Comment by dagraf** [comment]
Looks generelly really fine! Nice work! But there is always a "but": ;) 

1. I would like to have the possibility to change between the sharing option in the modal «Edit category», which opens when I hit the pen. See second bullet point in my last comment. Would this be possible?
2. When hovering over an existing item there is no information showing up anymore
![Uploading Bildschirmfoto 2020-10-07 um 17.05.53.png…]()
. Correct would be that the "Wert des Etiketts..." gets shown (see screenshot of productive annotation tool = "1 ist eins").

**Comment by Arnei** [comment]
>     1. I would like to have the possibility to change between the sharing option in the modal «Edit category», which opens when I hit the pen. See second bullet point in my last comment. Would this be possible?

I woudl also like that option. The problem is, the modal that opens when you hit the pen icon is not really an "Edit category" modal, but more of an "Edit scale" modal, which was not programmed with the idea of extendability in mind, so I'm not sure how much effort that would be. I'll talk with Julian about this.

>     2. When hovering over an existing item there is no information showing up anymore. Correct would be that the "Wert des Etiketts..." gets shown (see screenshot of productive annotation tool = "1 ist eins").

Interesting, there seems to be no straightforward reason why that should be the case. I will take a closer look at this.

**Comment by JulianKniephoff** [comment]
> > ```
> > 1. I would like to have the possibility to change between the sharing option in the modal «Edit category», which opens when I hit the pen. See second bullet point in my last comment. Would this be possible?
> > ```
> 
> I woudl also like that option. The problem is, the modal that opens when you hit the pen icon is not really an "Edit category" modal, but more of an "Edit scale" modal, which was not programmed with the idea of extendability in mind, so I'm not sure how much effort that would be. I'll talk with Julian about this.

My thoughts: That modal is not the right place for that setting. It's for selecting and editing scales. The code behind it is also not particularly nice, so I would want to avoid touching it for that reason, as well. :wink: We talked about this internally and both of us would prefer a nice modal for **all** the category settings, too. However, doing this right would take at least some effort, and I don't know if we can currently afford this, given our time constraints. And doing it -- pardon my French -- half-assed, where some settings are in the modal and some are where they are now, is not worth it, IMO. It would probably even confuse people, I think.

So if this solution, which is at least consistent with what we have for the track visibility, is workable for you at all, @dagraf, I would personally leave it for now. :thinking:

**Comment by dagraf** [comment]
I would prefer a modal for all category settings, too (see my specification comment from 13. Juli 2020). So we are on the same page here. I was just expecting (or hoping for) that you would be able to implement this "category settings"-modal while developping the new sharing-feature. Because I think the actual behavior (pen-icon opens a modal for creating and editing scales,, which are not mentioned elswhere) is quite confusing. 

Can you estimate how long it would take you to create proper category settings?

**Comment by JulianKniephoff** [comment]
@dagraf that depends on how exactly we want it to look and work. We will talk about it internally, but you can of course also add your opinion here.

Questions I would have right off the bat:

* Should editing labels also be pulled into that modal? I would tend to say yes.
* What about the scales? So the modal would obviously contain some way to select which scale the category uses, but would it also still allow to create new and edit existing scales, like the current modal does? In my mind, that doesn't really belong here. One idea would be to put the scale management in its own modal accessible from the main menu, or something like that. That's however less convenient, of course. You might still want to create a new scale from the category editor. That could still work, of course, but then we have a modal on top of a modal. Somehow that bugs me. x)

Thoughts?

**Comment by dagraf** [comment]
_- Should editing labels also be pulled into that modal? I would tend to say yes._ > I would also tend to "yes", if it can be implemented with reasonable effort (keeping the cost-benefit ratio in mind). We would then have similar functions behind the pen-icon. Because when hitting the pen-icon in the timeline I can edit name, description and sharing option of the track. But in my opinion most important would be to be able to edit these things in a "Edit category"-modal: Title of the category, select an already existing scale (as dropdown menu), select one of the 3 sharing options (as radio buttons)

_- What about the scales?_ > I newer liked/understood the way scales had to be created. I would suggest an own modal for scale management and that we find a different solution for creating and editing scales. What about an additional button "Create & edit scales" that shows up when a user activates the checkbox "edit"? And to end: What does bug you about the idea of have a modal on top of a different one? That the underlying modal does not know the with the upper modal newly created scale?

**Comment by JulianKniephoff** [comment]
A more globally accessible modal for managing scales would definitely be nice. We **could** hide that behind the edit mode, but why not just put it in the menu somewhere? :thinking: 

And the category settings modal would then have a dropdown to select existing scales, and maybe some kind of "Plus-Button" to to add a new one, which would then open the new scale modal on top of the category modal. I think I could live with that. My aversion towards modals on top of modals isn't really that hard of an opinion. **In general** I think it feels messy and can become confusing, but it might just be the right solution for the data model at hand. Technically it shouldn't be a problem, I think.

**Comment by JulianKniephoff** [comment]
Finally closed by #407, I think. :sweat_smile:
