### ISSUE TITLE
XLSX-Export: All rows containing informations are hidden

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#466]
If a user/admin does an export for Excel and opens it with Excel all rows containing informations are hidden. The column shown all left is the column "X". This leads to the perception, that the export did not work. In order to be able to see the export, the user first has to actively "Show" the hidden rows. See screencast: https://tube.switch.ch/videos/282116e3

Appears both ond Mac and Windows.

**Comment by dagraf** [comment]
Does this fix get implemented allready this friday (5.3.2021) during the newest SWITCHcast maintanance window?

**Comment by JulianKniephoff** [comment]
The Friday maintenance window has a different purpose, unfortunately. I will talk to Matthias whether we can find a good opportunity for this hotfix release in the near future, but this might have to wait until next week, since I'll be gone for the next two days.

In general this shouldn't take too long, though, so we **should** be able to accommodate this some time next week.
