### ISSUE TITLE
Sharing option: Additional explanation for new option

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#533]
When option "Show all users automatically" is actived, please show below the following message:
DE: Die Spur wird allen Benutzern automatisch und schreibgeschützt angezeigt. Andere Benutzer können also keine Änderungen vornehmen.
EN: The track is displayed to all users automatically and in read-only mode. So other users can not make any changes.

**Comment by dagraf** [comment]
Text is now there. But because is it in the same format and font as the option itself it is not clear on the first sight, what is the option and what the explanation. Could you please format the explanation slightly differently? For example in grey, in italics or a bit intended?

**Comment by dagraf** [comment]
Thx for your suggestion. I agree, it is worth thinking about how the naming of the access options could be optimised. But the naming you suggest doesn't really fit to what the options are doing. Let me explain what they do:

- Automatically display to all users: Makes a track public and takes care of showing this track to every user who opens the video in the annotation tool. But the track is still in read only mode for other users.
- Public: Makes a track public. But a user has to actively 'open' the track using the funcionality "Track management".

Do you have other ideas how to improve the naming?

**Comment by lkiesow** [comment]
Are the tracks in read-only mode if I select “Public” or “Share with admin”? Or can anyone/admin then edit them as well?

**Comment by dagraf** [comment]
Tracks are always in read-only mode.

**Comment by lkiesow** [comment]
In that case, let me make a suggestion based on my current understanding:

- Global preview (automatically shown to all users)
- Public (any user may access this)
- Shared with admin (admins may access this)
- Private (only you have access)

My idea is foremost to make a distinction between what the new state does in contrast to public.
If you want, we could also highlight the names a bit more. Something like:

- __Global preview__ (automatically shown to all users)
- __Public__ (any user may access this)
- __Shared with admin__ (admins may access this)
- __Private__ (only you have access)

…and now you tell me what I did fail to understand this time :wink:

**Comment by dagraf** [comment]
:) No misunderstandings anymore.
I like your suggestion including the highlighting of the names. But I am not quite sure about the name "Global preview", mainly because it is not e "preview" (according to leo.org: Vorschau, Probevorführung, ...). Here my suggestion: 

- **Public & by default** (automatically shown to all users)
- **Public & on demand** (any user may access this)
- **Shared with admin** (admins may access this)
- **Private** (only owner has access)

German:
- **Öffentlich & automatisch** (wird allen Usern automatisch angezeigt)
- **Öffentlich & on demand** (alle User können darauf zugreifen)
- **Mit Administratoren geteilt** (Administratoren können darauf zugreifen)
- **Privat** (nur Besitzer hat Zugriff)

What do you think?

**Comment by lkiesow** [comment]
The idea of “Global preview” came from my idea that this would likely be used to showcase a track. For example, so that students would start with this track and know what their lecturer is looking for. But maybe that again was a misjudgment.

So, here are a few last suggestion before I'll just take yours.

I think the “&” is very odd. “Public & by default” could easily be misread or misinterpreted as “Public by default”. That means something else. If you do notice the “&”, that leaves you with the statement “by default”. Which makes you ask: “By default, what?” From there you could go to “displayed by default” which at that point becomes more or less the following explanation, making this a somewhat redundant message.

If we want to stick to short names with brief explanations, we could make the first public implicit:

- **Visible by default** (automatically shown to all users)
- **Public** (any user may access this)
- **Shared with admin** (admins may access this)
- **Private** (only owner has access)

…or we could use this one, again making sure the option names are quite distinct. The meaning of the first two is actually pretty similar. But the short description should clarify this. I think for users, talking to each other, it's easy to remember the difference.

- **Public** (automatically shown to all users)
- **Shared with anyone** (any user may access this)
- **Shared with admin** (admins may access this)
- **Private** (only owner has access)

…or this one, which highlights the difference between “shared” which leaves the choice to users and “pushed” which forces this on users. Unfortunately, I cannot work out a good German translation for this.

- **Pushed to anyone** (automatically shown to all users)
- **Shared with anyone** (any user may access this)
- **Shared with admin** (admins may access this)
- **Not shared** (only owner has access)

…finally, circling back to the original options, but highlighting the differences between the options a bit stronger and leaving out confusing bits, here is one with longer options, but no more additional descriptions:

- Automatically displayed to all users
- Optionally accessible to all users
- Optionally accessible to administrators
- Only accessible to owner

---

German:

- **Standardmäßig sichtbar** (wird allen Nutzern automatisch angezeigt)
- **Öffentlich** (alle Nutzern können zugreifen)
- **Mit Admin geteilt** (Administratoren können zugreifen)
- **Privat** (nur Besitzer hat Zugriff)

oder

- **Öffentlich** (wird allen Nutzern automatisch angezeigt)
- **Geteilt mit allen** (alle Nutzern können zugreifen)
- **Geteilt mit Admin** (Administratoren können zugreifen)
- **Privat** (nur Besitzer hat Zugriff)

oder

- Automatisch bei allen Nutzern angezeigt
- Optional zugreifbar durch andere Nutzer
- Optional zugreifbar durch Administratoren
- Nur Besitzer hat Zugriff

Now, pick whatever you like and I'll include that.

**Comment by dagraf** [comment]
Thanks a lot for all your work and great ideas. I think we are getting close to a reasonable solution. You're right, the "&" could be overseen easily.

I like your first and second suggestion very much. After a short discussion with my colleague Yvonne (who is an expert in interaction design) we would suggest a combination of your first and second suggestion. In doing so we get rid of the public, which in fact is true for two access options. This would lead to this:

- **Visible by default** (automatically shown to all users)
- **Shared with anyone** (any user may access this)
- **Shared with admin** (admins may access this)
- **Private** (only owner has access)

DE (note the small change to "Standardmässig angezeigt" und "Mit allen geteilt"):

- **Standardmäßig angezeigt** (wird allen Nutzern automatisch angezeigt)
- **Mit allen geteilt** (alle Nutzer können zugreifen)
- **Mit Admin geteilt** (Administratoren können zugreifen)
- **Privat** (nur Besitzer hat Zugriff)

What do you think?

**Comment by lkiesow** [comment]
Used those.

**Comment by dagraf** [comment]
Looks fine, thx!
