### ISSUE TITLE
Make categories slightly wider

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#542]
With the new "Triangle" and the olt "Eye-Icon" there is even less space for showing the title of a category. Therefore with cateogries with longer names, only the first 4-5 letters are shown followed by three dots (see screenshot). Solution: make categories by default slightly wider. 
<img width="257" alt="Bildschirmfoto 2021-10-28 um 11 49 41" src="https://user-images.githubusercontent.com/15246287/139232265-ac2e7170-882c-40cb-bc89-1bcad61b4931.png">

**Comment by JulianKniephoff** [comment]
One could also just let the categories be as wide as they (and their labels) need. Of course that would mean that they are potentially of different widths. @dagraf thoughts? :thinking: 

Otherwise: Do you have any preference for a width? Like, can you give me a word that should always be visible at least or something like that?

**Comment by dagraf** [comment]
Different lenghts would be e reasonable solution as long teachers do not choose to long category labels. Therfore I would prefer the fix width. What about "Kategorie A" as the word, that should be always visible?

**Comment by dagraf** [comment]
Thx. Looks better now.
