### ISSUE TITLE
Affiliation of category "Belongs to series" does not work

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#551]
Categories set to "Belongs to series" are not shown in videos of the same series.

**Comment by dagraf** [comment]
Additional observation: When I try to change the affiliation from "Belongs to series" to "Belongs to the video" and click on save, the window gets close. When I reopen the window "Edit category" the option "Belongs to series" is still activated. Somehow this change does not get saved.

**Comment by JulianKniephoff** [comment]
> 

At least this should now be fixed on staging.

**Comment by dagraf** [comment]
> > Additional observation: When I try to change the affiliation from "Belongs to series" to "Belongs to the video" and click on save, the window gets close. When I reopen the window "Edit category" the option "Belongs to series" is still activated. Somehow this change does not get saved.
> 
> At least this should now be fixed on staging.

Thx. I can confirm this part of the fix.

**Comment by dagraf** [comment]
The basic behaviour works now as expected. But there is a new bug which occurs, if I have at least two videos (1 and 2) and if I edit the affiliation setting of category belongig to the series in the video, where I did NOT create it. 
For example (see screencast): I create a series-category in video 1 and edit the affiliation setting to "Belongs to the video" in video 2: At first everything seems fine. But when I reload the browser in video 2 all existing labels show up twice.

https://user-images.githubusercontent.com/15246287/150859997-ab6bfe04-1479-4489-91b5-dba51060b2e1.mp4

**Comment by lkiesow** [comment]
From what I understand, the idea was that there should still be a difference between the event which created the category in the first place and the events where it shows up because they are part of the series. What now happens is likely that you turn the category into a video-local category on the second video, but when you reload, the series categories are still pushed to the video two again. That is why you end up with the duplicated categories.

I can see that this is confusing, but I also don't quite get what the original intend for this was? Was it that you shouldn't be able to turn series categories local at all, so that they don't suddenly disappear or duplicate? Was it that you wouldn't be able to edit the category on the second video? Was it that you just wouldn't be able to change the categories' affiliation on the second video? Was it that you could turn them local?

So, what I'm asking is, can you describe how you would expect this to behave?

**Comment by dagraf** [comment]
(Our/The) idea was that it does not matter in which event a category belongig to a series is created. Mainly because we do not believe that teachers can recall in which event they have created the category. Therefore you should be able to turn a category belongig to series to a local category (= belonging to a video) in all events.

**Comment by lkiesow** [comment]
Is the following an accurate description of what you would expect to happen?

Step 1:

- Create category `A` and labels `B` and `C`
- Mark as “belongs to series”
- __Result__: Category `A` shows up on all events of the series, with labels `B` and `C`

Step 2:

- Go to a random event `X` of the series
- Edit category `A`
- Mark as “belongs to video”
- __Result__: Category `A` becomes a local category on video `X` with labels `B` and `C`
- __Result__: Other events of that series will not show the category any longer

Step 3:

- Go to event `X` of the series
- Edit category `A`
- Mark as “belongs to series”
- __Result__: Category `A` shows up on all events of the series, with labels `B` and `C`

**Comment by dagraf** [comment]
Exactly. Thanks for summing it up in detail.

**Comment by lkiesow** [comment]
Bad news: I can't reproduce the issue. I've tries different test systems, different browsers, …
Good news is that I might have found the issue anyway.

If I'm righter than this could be a raise condition happening when saving the category itself takes some time but saving the labels is pretty fast. I hope that https://github.com/opencast/annotation-tool/pull/569 fixes the issue.

**Comment by dagraf** [comment]
Looks fine now, thx!
