### ISSUE TITLE
Annotation-Tool Errors in building process (Still Build Success)

### ISSUE THREAD

**Issue by TomBogatsch** [opencast/annotation-tool#555]
Running Opencast10.8

When executing "mvn clean install -DdeployTo=/usr/share/opencast" there are errors in testing during the buidling process. However in the end the build is still a success. I included the buildlog

[Buildlog.txt](https://github.com/opencast/annotation-tool/files/7912898/Buildlog.txt)

**Comment by JulianKniephoff** [comment]
Assuming you mean the EclipseLink errors this is "expected."

EclipseLink logs queries that fail/lead to exceptions in the Java code, and in the tests we have some queries that intentionally fail so that we can test the tool's reaction to it, put simply.

Closing. Feel free to reopen if this is not what you meant.
